name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ python3-pip python3-venv
        python3 -m venv venv
        source venv/bin/activate
        pip3 install conan
        conan profile detect

    - name: Install Conan Packages
      run: |
        source venv/bin/activate
        conan install . --build=missing -s build_type=Debug

    - name: Configure CMake
      run: cmake --preset conan-debug

    - name: Build
      run: cmake --build --preset conan-debug

    - name: Test
      run: ctest --test-dir build/Debug --output-on-failure
